project_id = "uomdyqdvorusucuudwnz"

[functions.text-to-speech]
verify_jwt = false

[functions.get-voices]
verify_jwt = false

[functions.health-realtime]
verify_jwt = false

[functions.env-debug]
verify_jwt = false

[functions.eleven-agent-token]
verify_jwt = false
