// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Project defaults — used when the environment does not override them.
const DEFAULT_SUPABASE_URL = "https://uomdyqdvorusucuudwnz.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbWR5cWR2b3J1c3VjdXVkd256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTQ4NDcsImV4cCI6MjA2NzE3MDg0N30.Xsc3aLEFxY-5NoiUkGXWqWMkwyWK142fVbps6SGBhHc";

// Allow pointing the app at a different Supabase project per environment via
// VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY (see .env.example). Apply the
// override only when BOTH are set, so we never mix a custom URL with the default
// key (or vice versa) and accidentally cross environments. A partial override is
// ignored with a warning, and with neither set we use the default pair.
const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let SUPABASE_URL = DEFAULT_SUPABASE_URL;
let SUPABASE_PUBLISHABLE_KEY = DEFAULT_SUPABASE_PUBLISHABLE_KEY;
if (envUrl && envKey) {
  SUPABASE_URL = envUrl;
  SUPABASE_PUBLISHABLE_KEY = envKey;
} else if (envUrl || envKey) {
  console.warn(
    "[supabase] Ignoring partial VITE_SUPABASE_* override — set both " +
      "VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY together, or neither."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});